export interface AutoMeaning {
  key: string;
  label: string;
  meaning: string;
}

export const AUTO_MEANINGS: AutoMeaning[] = [
  {
    key: "exactId",
    label: "Exact ID",
    meaning: "A deterministic identifier for this exact cell arrangement.",
  },
  {
    key: "occupancy",
    label: "Occupancy",
    meaning: "Number of occupied cells.",
  },
  {
    key: "connected",
    label: "Connected",
    meaning:
      "Yes when all occupied cells belong to one orthogonally connected component. Empty arrangements show —.",
  },
  {
    key: "components",
    label: "Components",
    meaning: "Number of separate occupied groups using orthogonal adjacency.",
  },
  {
    key: "center",
    label: "Center",
    meaning: "State of the unique center where one exists.",
  },
  {
    key: "corners",
    label: "Corner occupied count",
    meaning: "Number of occupied corner positions.",
  },
  {
    key: "edges",
    label: "Edge occupied count",
    meaning: "Number of occupied non-corner boundary positions.",
  },
  {
    key: "rotationalSymmetry",
    label: "Rotational symmetry order",
    meaning: "Number of those rotations that leave the arrangement unchanged.",
  },
  {
    key: "reflectionSymmetry",
    label: "Reflection symmetry",
    meaning: "Whether at least one square reflection leaves the exact arrangement unchanged.",
  },
  {
    key: "rotationOrbitSize",
    label: "Rotation orbit size",
    meaning:
      "Number of distinct exact arrangements generated by 0°, 90°, 180°, and 270° rotation.",
  },
  {
    key: "dihedralOrbitSize",
    label: "Dihedral orbit size",
    meaning: "Number of distinct exact arrangements generated by the square D4 symmetry group.",
  },
  {
    key: "rotationClass",
    label: "Rotation class",
    meaning: "All exact arrangements equivalent under rotation.",
  },
  {
    key: "dihedralClass",
    label: "Rotation + Reflection class",
    meaning: "All exact arrangements equivalent under the full square D4 symmetry group.",
  },
];
